### PR TITLE
Color filter

### PR DESCRIPTION
**Pull request by rozPierog**
# Summary

Added ability to recolor animation via one prop (solves https://github.com/react-native-community/lottie-react-native/issues/180)

But I need help with implementing this into iOS. When trying to build iOS app, all I've got is 
```swift

❌  error: Build input file cannot be found: '/Users/leon/Documents/<project_path>/node_modules/lottie-react-native/src/ios/LottieReactNative/LRNAnimationViewManager.m'


▸ Compiling LRNContainerView.m

❌  error: Build input file cannot be found: '/Users/leon/Documents/<project_path>/node_modules/lottie-react-native/src/ios/LottieReactNative/LRNContainerView.m'


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening <project_name>.xcworkspace
```

Is there anyone familiar with iOS that would point me in the right direction? 
@prateekkohli1989 - you are the person that was responsible for rewriting whole module into swift, maybe you have some insider info on how to fix this.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I mentioned this change in `CHANGELOG.md`
- [ ] ~I added a sample use of the API in the example project (`example/App.js`)~ - couldn't get example to work. iOS `Could not find iPhone 6 simulator` and on Android it's just too old gradle version that isn't compatible with my java 10 environment.

### CODE REVIEW

**Comment by rozPierog** [comment]
@emilioicai - can you help me with this? Or can you ping someone who can? I would love to get this merged

**Comment by emilioicai** [comment]
sure, I will give it a try

**Comment by emilioicai** [comment]
sure, I will give it a try

**Comment by rozPierog** [comment]
@emilioicai just checking in if you are still interested in helping out with this PR

**Comment by emilioicai** [comment]
Hi @rozPierog I'm very eager to have this merged but I cannot make it work in iOS, did you have any luck?

**Comment by rozPierog** [comment]
Sadly, no 😞

**Comment by robertherber** [comment]
Any progress on the last few commits @rozPierog? Would love to be able to use this :)

**Comment by rozPierog** [comment]
@robertherber I would love to see it merged, but sadly I don't have time right now to fix iOS side of things. Feel free to fork my fork and submit your own PR

**Pull request closed without merging**
