### PR TITLE
Add Pause & Resume commands and OnLayout prop

### PR DESCRIPTION
**Pull request by AAAstorga**
# Summary

My team needed the ability to pause and resume animations from our RN project. I added two new commands. We also needed the position information, so I added an onLayout prop and exposed it.

## Test Plan

I have these changes running in a build and they work as intended.

### What's required for testing (prerequisites)?

Get a ref to the LottieView and call pause/resume.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X ] I added the documentation in `README.md`
- [ X] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by AAAstorga** [comment]
Hello,
Is there a timeline for when this can be reviewed?

Thanks!

**Comment by emilioicai** [comment]
@AAAstorga this is tested an ready to be merged but may I ask you to add some documentation for it?

**Comment by AAAstorga** [comment]
Hey @emilioicai Thanks for the review. What kind of documentation are you referring to? I updated the docs to describe this new functionality. Let me know what other kind of documentation you are looking for?

Cheers!

> @AAAstorga this is tested and ready to be merged but may I ask you to add some documentation for it?

**Comment by emilioicai** [comment]
Oh! sorry, I missed that file, everything is fine. Thanks @AAAstorga !

**Comment by Yandamuri** [comment]
@emilioicai seems like still it hasn't been released but documentation has been updated. When i try to use pause or resume functions I am getting error. Can you let me know when can we get this change?

**Comment by emilioicai** [comment]
I'm planning a new release by tomorrow if everything goes according to the plan

**Comment by Yandamuri** [comment]
@emilioicai Great to hear that...hope everything goes according to the plan. BTW Can you have a loo at this [issue](https://github.com/react-native-community/lottie-react-native/issues/642). I am very new to this package and it's being difficult for me to make it work.

Thank You.

**Pull request merged**
