### PR TITLE
Enable RN projects to define the Android AppCompat Library version (and fix dependency issues with RN 0.59.x) and revert android lottie to 2.5.6

### PR DESCRIPTION
**Pull request by lorenc-tomasz**

### CODE REVIEW

**Comment by lorenc-tomasz** [comment]
@emilioicai  Any chance that this will be added to a new bug fix version once it gets merged?

**Comment by emilioicai** [comment]
@lorenc-tomasz sure, this will be included in the next release, thanks for your help!

**Comment by jliberacki** [comment]
@emilioicai when can we expect new release?

**Comment by emilioicai** [comment]
@jliberacki I plan on releasing this weekend :)

**Pull request merged**
