### PR TITLE
fix android need minSdk >= 26

### PR DESCRIPTION
**Pull request by canyara**
fix android need minSdk >= 26

### CODE REVIEW

**Comment by simonbuerger** [comment]
I see Android version 3.0.0-beta1 recently landed for lottie-android

@gpeal @emilioicai what are the breaking changes in that release? Can lottie-react-native safely be updated or will some changes be required in this repo (beyond the version bump)?

**Comment by emilioicai** [comment]
@simonbuerger we are testing how `lottie-react-native` works with `lottie-android` 3.0. Until we are sure it's safe to update we will stick with the dependency to 2.6.0

**Comment by gpeal** [comment]
@emilioicai 3.0 beta 1 should be pretty stable. It passes all of the thousands of regression tests and we're using it in prod at Tonal. Nothing is broken *to my knowledge*

**Comment by emilioicai** [comment]
@gpeal got it. I will give it a try and update the `lottie-react-native` with 3.0

**Comment by gpeal** [comment]
@emilioicai Just read the [changelog](https://github.com/airbnb/lottie-android/blob/master/CHANGELOG.md) notes as there are a couple of APIs that have changed but they're pretty easy changes.

**Comment by evanjmg** [comment]
can we merge this anyways?

**Pull request merged**
